services:

  # =================================================== #
  #  Fabric Server                                      #
  # =================================================== #

  fabric:
    container_name: mc_fabric
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    depends_on:
      init-nfs:
        condition: service_completed_successfully
    environment:
      ENABLE_ROLLING_LOGS: "TRUE"
      JVM_OPTS: "-XX:MaxRAMPercentage=75"
      TYPE: "FABRIC"
      EULA: "TRUE"
      VERSION: 1.21.11 # a default is "LATEST"
      MOTD: "The World of Fabric Server with Crossplay"
      MAX_PLAYERS: 5
      MAX_WORLD_SIZE: 10000
      ENABLE_COMMAND_BLOCK: "TRUE"
      SNOOPER_ENABLED: "FALSE"
      VIEW_DISTANCE: 12
      PVP: "FALSE"
      LEVEL: "world" # a default is "world"
      #ONLINE_MODE: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      USE_NATIVE_TRANSPORT: "TRUE"
      STOP_SERVER_ANNOUNCE_DELAY: 60
      # WHITELIST: "player1,player2"
      GUI: "FALSE"
      MODS: |
      SERVER_PORT: "25565"
    #deploy:
    #  resources:
    #    limits:
    #      memory: 8G
    ports:
      - "25565:25565/tcp"
      - "25575:25575/udp"
    volumes:
      - minecraft-server:/data
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
  # The helper container that creates the folder automatically
  init-nfs:
    image: alpine
    volumes:
      - nfs-root:/mnt/nfs
    command: mkdir -p /mnt/nfs/minecraft-server

volumes:
  nfs-root:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.10.201,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: ":/Volumes/"
  minecraft-server:
    driver_opts:
      type: nfs
      o: addr=192.168.10.201,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: ":/Volumes/minecraft-server/"
